version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5050"  # Map host port 8080 to container port 5050
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: on-failure
